### ISSUE TITLE
Hacktoberfest!?

### ISSUE THREAD

**Issue by sloorush** [IEEE-VIT/.github#20]
Should we change the text to something based on Hacktoberfest? 

I feel the illustration works well for Hacktoberfest.

Reference: https://hacktoberfest.com/

cc: @kavxprxya @ananya190

**Comment by sloorush** [comment]
Open to suggestions!

cc: @Harsh-1309 @ShubhamPalriwala

**Comment by Harsh-1309** [comment]
Same illustration as on the hacktoberfest site works ig? Along with a couple of lines of description of hacktoberfest @sloorush

**Comment by sloorush** [comment]
> Same illustration as on the hacktoberfest site works ig?

I was wondering if we could keep our illustration the way it is and change the text and description.

**Comment by ananya190** [comment]
can i change just the text for now, if kp's up for it in the rest of the week, we'll think about maybe incorporating hacktoberfest into the current illustration?

**Comment by sloorush** [comment]
Yep sounds good!
